# Generated by Django 4.1.7 on 2023-03-13 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.DeleteModel(
            name='Outfit',
        ),
        migrations.AlterField(
            model_name='match',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 13, 26, 26, 799131)),
        ),
    ]
