# Generated by Django 4.1.7 on 2023-03-13 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shop_delete_outfit_alter_match_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 13, 33, 0, 428175)),
        ),
    ]
